package netbox

import (
	"fmt"
	"io"
	"strings"
)

// WriteReference writes the supported versions page,
// docs/reference/supported-versions.md, from Supported.
func WriteReference(w io.Writer) error {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	p("---\ntitle: Supported versions\nweight: 30\n---\n\n")
	p("<!-- Generated by internal/cmd/gendocs from netbox.Supported in internal/netbox.\n")
	p("     Don't edit this page: change the list, then run `make generate`. -->\n\n")
	p("# Supported versions\n\n")
	p("nbpdns reads DNS data from these releases of NetBox and the\n")
	p("[NetBox DNS plugin](https://github.com/peteeckel/netbox-plugin-dns). The\n")
	p("development lab runs each pair, and the integration tests read from every one.\n\n")
	p("| NetBox | NetBox DNS plugin |\n|---|---|\n")
	for _, r := range Supported {
		p("| %s.x | %s.x |\n", r.NetBox, r.Plugin)
	}
	p("\nnbpdns checks NetBox and the plugin against this table separately, since\n")
	p("NetBox won't load a plugin release that doesn't support it. Before it reads,\n")
	p("each command checks the releases that NetBox reports:\n\n")
	p("- If the plugin isn't installed, the command fails.\n")
	p("- If NetBox or the plugin isn't a release in the table, the command logs a\n")
	p("  warning and carries on, since reading may still work.\n")
	p("  `nbpdns netbox check` reports it as a failed check.\n\n")
	p("nbpdns reads through NetBox's REST API, with an API token. Use a v2 token,\n")
	p("which starts with `nbt_`. A v1 token still works, with a warning.\n")
	_, err := io.WriteString(w, b.String())
	return err
}
