package api

import (
	"errors"
	"fmt"
	"io"
	"strings"

	"go.yaml.in/yaml/v3"
)

// WriteReference writes the API's reference page, docs/reference/api.md,
// from its OpenAPI document: every operation, with what it needs, its
// parameters, its request body and its responses, and every schema, with
// its fields, in the document's order.
func WriteReference(w io.Writer) error {
	var doc yaml.Node
	if err := yaml.Unmarshal(spec, &doc); err != nil {
		return err
	}
	if len(doc.Content) == 0 {
		return errors.New("the OpenAPI document is empty")
	}
	root := doc.Content[0]
	ref := &reference{root: root}
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	p("---\ntitle: API\nweight: 45\n---\n\n")
	p("<!-- Generated by internal/cmd/gendocs from api/openapi.yaml, the API's source of truth.\n")
	p("     Don't edit this page: change the OpenAPI document, then run `make generate`. -->\n\n")
	p("# API\n\n")
	p("`nbpdns serve` serves its API at `/api`, on `server.listen`. This page is\n")
	p("generated from `api/openapi.yaml`, the API's source of truth, version %s.\n", node(node(root, "info"), "version").Value)
	p("The service serves the same document at `/api/openapi.yaml`, and a\n")
	p("reference to browse at `/api/docs`.\n")
	p("[How nbpdns's API is designed](../explanation/how-nbpdns-api-is-designed.md)\n")
	p("explains its conventions.\n\n")
	p("> [!WARNING]\n")
	p("> The API has no authentication until M10, and it names your server\n")
	p("> groups, zones, and records. Keep `server.listen` on a trusted network.\n")
	p("> Only NetBox's webhooks need a signature.\n\n")
	p("## Conventions\n\n")
	p("- Bodies are JSON, with `snake_case` fields. Every field that a\n")
	p("  response's schema lists is always present: one with nothing to say is\n")
	p("  `null`.\n")
	p("- Times are RFC 3339, in UTC.\n")
	p("- A list takes `limit`, from 1 to 1000, 100 by default, and `cursor`, and\n")
	p("  answers a page: its `items`, and the absolute URLs of itself, `self`,\n")
	p("  and of the next page, `next`, which is `null` on the last page.\n")
	p("- Every error is an RFC 9457 problem, as `application/problem+json`.\n")
	p("- Each request may send an `X-Flow-ID`; the response returns it, or a\n")
	p("  new one, which is the request's `request_id` in the logs.\n\n")

	p("## Operations\n\n")
	for path, item := range pairs(node(root, "paths")) {
		for method, op := range pairs(item) {
			p("### `%s /api%s`\n\n", strings.ToUpper(method), path)
			p("%s. Operation `%s`.\n\n", strings.TrimSuffix(node(op, "summary").Value, "."), node(op, "operationId").Value)
			if d := node(op, "description"); d != nil {
				p("%s\n\n", strings.TrimSpace(d.Value))
			}
			// An operation without its own security has the document's: none.
			for _, req := range contentOf(node(op, "security")) {
				for name := range pairs(req) {
					scheme := node(node(node(root, "components"), "securitySchemes"), name)
					p("Needs the `%s` %s. %s\n\n", node(scheme, "name").Value, node(scheme, "in").Value, oneLine(node(scheme, "description")))
				}
			}
			p("| Parameter | In | Type | Description |\n|---|---|---|---|\n")
			for _, param := range node(op, "parameters").Content {
				param = ref.resolve(param)
				in := node(param, "in").Value
				if node(param, "required") != nil && node(param, "required").Value == "true" {
					in += ", required"
				}
				p("| `%s` | %s | %s | %s |\n", node(param, "name").Value, in, ref.typeOf(node(param, "schema")), oneLine(node(param, "description")))
			}
			if body := node(op, "requestBody"); body != nil {
				for ctype, media := range pairs(node(body, "content")) {
					p("\nThe request's body is %s, `%s`. %s\n", ref.typeOf(node(media, "schema")), ctype, oneLine(node(body, "description")))
				}
			}
			p("\n| Response | Description | Body |\n|---|---|---|\n")
			for code, resp := range pairs(node(op, "responses")) {
				resp = ref.resolve(resp)
				body := "none"
				for ctype, media := range pairs(node(resp, "content")) {
					body = ref.typeOf(node(media, "schema")) + ", `" + ctype + "`"
				}
				p("| %s | %s | %s |\n", code, oneLine(node(resp, "description")), body)
			}
			p("\n")
		}
	}

	p("## Schemas\n\n")
	for name, s := range pairs(node(node(root, "components"), "schemas")) {
		p("### `%s`\n\n%s\n\n", name, strings.TrimSpace(node(s, "description").Value))
		if enum := node(s, "enum"); enum != nil {
			p("One of %s.\n\n", values(enum))
			continue
		}
		props := node(s, "properties")
		if all := node(s, "allOf"); all != nil {
			for _, part := range all.Content {
				if r := node(part, "$ref"); r != nil {
					p("The fields of %s, and:\n\n", ref.typeOf(part))
					continue
				}
				props = node(part, "properties")
			}
		}
		p("| Field | Type | Description |\n|---|---|---|\n")
		for field, f := range pairs(props) {
			// A field that only refers to a schema has that schema's description.
			desc := node(f, "description")
			if desc == nil {
				desc = node(ref.resolve(f), "description")
			}
			p("| `%s` | %s | %s |\n", field, ref.typeOf(f), oneLine(desc))
		}
		p("\n")
	}
	_, err := io.WriteString(w, strings.TrimRight(b.String(), "\n")+"\n")
	return err
}

// reference resolves references in the OpenAPI document root.
type reference struct{ root *yaml.Node }

// resolve returns the object that n refers to, if n is a reference, or n.
func (r *reference) resolve(n *yaml.Node) *yaml.Node {
	ref := node(n, "$ref")
	if ref == nil {
		return n
	}
	out := r.root
	for _, part := range strings.Split(strings.TrimPrefix(ref.Value, "#/"), "/") {
		out = node(out, part)
	}
	return out
}

// typeOf describes schema s's type, linking to the schemas it names.
func (r *reference) typeOf(s *yaml.Node) string {
	if s == nil {
		return "`any`"
	}
	if ref := node(s, "$ref"); ref != nil {
		name := ref.Value[strings.LastIndex(ref.Value, "/")+1:]
		return "[`" + name + "`](#" + strings.ToLower(name) + ")"
	}
	if one := node(s, "oneOf"); one != nil {
		var kinds []string
		null := false
		for _, alt := range one.Content {
			if t := node(alt, "type"); t != nil && t.Value == "null" {
				null = true
				continue
			}
			kinds = append(kinds, r.typeOf(alt))
		}
		out := strings.Join(kinds, " or ")
		if null {
			out += ", or null"
		}
		return out
	}
	typ, null := "", false
	switch t := node(s, "type"); {
	case t == nil:
		typ = "object"
	case t.Kind == yaml.SequenceNode:
		for _, c := range t.Content {
			if c.Value == "null" {
				null = true
			} else {
				typ = c.Value
			}
		}
	default:
		typ = t.Value
	}
	switch {
	case typ == "array":
		typ = "array of " + r.typeOf(node(s, "items"))
	case node(s, "enum") != nil:
		typ = values(node(s, "enum"))
	case node(s, "format") != nil:
		typ = "`" + typ + "` (`" + node(s, "format").Value + "`)"
	default:
		typ = "`" + typ + "`"
	}
	if null {
		typ += ", or null"
	}
	return typ
}

// contentOf returns the items of the sequence n, or none if n is nil.
func contentOf(n *yaml.Node) []*yaml.Node {
	if n == nil {
		return nil
	}
	return n.Content
}

// node returns the value of key in the mapping n, or nil.
func node(n *yaml.Node, key string) *yaml.Node {
	if n == nil || n.Kind != yaml.MappingNode {
		return nil
	}
	for i := 0; i+1 < len(n.Content); i += 2 {
		if n.Content[i].Value == key {
			return n.Content[i+1]
		}
	}
	return nil
}

// pairs returns the keys and values of the mapping n, in order.
func pairs(n *yaml.Node) func(func(string, *yaml.Node) bool) {
	return func(yield func(string, *yaml.Node) bool) {
		if n == nil || n.Kind != yaml.MappingNode {
			return
		}
		for i := 0; i+1 < len(n.Content); i += 2 {
			if !yield(n.Content[i].Value, n.Content[i+1]) {
				return
			}
		}
	}
}

// values lists an enum's values, as code.
func values(n *yaml.Node) string {
	var vs []string
	for _, c := range n.Content {
		if c.Tag != "!!null" {
			vs = append(vs, "`"+c.Value+"`")
		}
	}
	if len(vs) < 2 {
		return strings.Join(vs, "")
	}
	return strings.Join(vs[:len(vs)-1], ", ") + ", or " + vs[len(vs)-1]
}

// oneLine returns a description on one line, for a table cell, with its
// pipes escaped.
func oneLine(n *yaml.Node) string {
	if n == nil {
		return ""
	}
	return strings.ReplaceAll(strings.Join(strings.Fields(n.Value), " "), "|", `\|`)
}
