package cli

import (
	"fmt"
	"io"
	"strings"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"

	"github.com/zeddD1abl0/netbox-powerdns-ai/internal/config"
)

// WriteReference writes the command-line reference page,
// docs/reference/command-line.md, from root's command tree.
func WriteReference(w io.Writer, root *cobra.Command) error {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	p("---\ntitle: Command line\nweight: 20\n---\n\n")
	p("<!-- Generated by internal/cmd/gendocs from the Cobra commands in internal/cli.\n")
	p("     Don't edit this page: change the commands, then run `make generate`. -->\n\n")
	p("# Command line\n\n")
	p("nbpdns writes each command's output to standard output, and its logs and errors\n")
	p("to standard error. Every command accepts `--help`. nbpdns exits with one of\n")
	p("these statuses:\n\n")
	p("| Status | Meaning |\n|---|---|\n")
	p("| %d | The command succeeded. |\n", exitOK)
	p("| %d | The command failed. Standard error says why. |\n", exitError)
	p("| %d | The command line was wrong: an unknown command or flag, or a bad argument. |\n", exitUsage)
	p("| %d | `nbpdns drift` compared everything, and found drift. |\n\n", exitDrift)

	p("## Global flags\n\n")
	p("Every command accepts these flags. Each sets a configuration key, as described\n")
	p("in the [configuration reference](configuration.md).\n\n")
	flagTable(&b, root.PersistentFlags())

	p("\n## Commands\n")
	for _, c := range commands(root) {
		p("\n### `%s`\n\n", c.CommandPath())
		// Cobra's --help shows Long instead of Short, so Long restates it.
		if c.Long != "" && !isCompletion(c) {
			p("%s\n", strings.TrimSpace(c.Long))
		} else {
			p("%s.\n", strings.TrimSuffix(c.Short, "."))
		}
		use := c.UseLine()
		if c.HasAvailableSubCommands() {
			use = c.CommandPath() + " [command]"
		}
		p("\n```text\n%s\n```\n", use)
		local := pflag.NewFlagSet(c.Name(), pflag.ContinueOnError)
		c.LocalNonPersistentFlags().VisitAll(func(f *pflag.Flag) {
			if f.Name != "help" {
				local.AddFlag(f)
			}
		})
		if local.HasAvailableFlags() {
			p("\n")
			flagTable(&b, local)
		}
		var subs []string
		for _, s := range c.Commands() {
			if s.IsAvailableCommand() {
				subs = append(subs, fmt.Sprintf("[`%s`](#%s)", s.Name(), strings.ReplaceAll(s.CommandPath(), " ", "-")))
			}
		}
		if len(subs) > 0 {
			p("\nSubcommands: %s.\n", list(subs))
		}
	}
	_, err := io.WriteString(w, b.String())
	return err
}

// commands returns every available command under root, depth first, in
// name order.
func commands(root *cobra.Command) []*cobra.Command {
	var out []*cobra.Command
	for _, c := range root.Commands() {
		if !c.IsAvailableCommand() || c.IsAdditionalHelpTopicCommand() {
			continue
		}
		out = append(out, c)
		out = append(out, commands(c)...)
	}
	return out
}

// isCompletion reports whether c is one of Cobra's per-shell completion
// commands, whose long help is shell instructions for --help.
func isCompletion(c *cobra.Command) bool {
	return c.HasParent() && c.Parent().Name() == "completion"
}

// flagTable writes a table of fs's visible flags.
func flagTable(b *strings.Builder, fs *pflag.FlagSet) {
	b.WriteString("| Flag | Type | Default | Description |\n|---|---|---|---|\n")
	fs.VisitAll(func(f *pflag.Flag) {
		if f.Hidden {
			return
		}
		name := "`--" + f.Name + "`"
		if f.Shorthand != "" {
			name = "`-" + f.Shorthand + "`, " + name
		}
		def := "none"
		if f.DefValue != "" && f.DefValue != "false" {
			def = "`" + f.DefValue + "`"
		}
		usage := f.Usage
		if md := f.Annotations[config.MarkdownUsage]; len(md) == 1 {
			usage = md[0]
		}
		fmt.Fprintf(b, "| %s | `%s` | %s | %s |\n", name, f.Value.Type(), def, strings.ReplaceAll(usage, "|", `\|`))
	})
}

// list joins items as an English list, with a serial comma.
func list(items []string) string {
	switch len(items) {
	case 1:
		return items[0]
	case 2:
		return items[0] + " and " + items[1]
	}
	return strings.Join(items[:len(items)-1], ", ") + ", and " + items[len(items)-1]
}
