package config

import (
	"fmt"
	"io"
	"strings"
)

// WriteReference writes the configuration reference page,
// docs/reference/configuration.md, from the key registry.
func WriteReference(w io.Writer) error {
	ks := Keys()
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	p("---\ntitle: Configuration\nweight: 10\n---\n\n")
	p("<!-- Generated by internal/cmd/gendocs from the key registry in internal/config.\n")
	p("     Don't edit this page: change the registry, then run `make generate`. -->\n\n")
	p("# Configuration\n\n")
	p("Every setting has a key, such as `netbox.url`. nbpdns takes each key's value from\n")
	p("the first of these that sets it:\n\n")
	p("1. a flag, such as `--netbox-url`;\n")
	p("2. an environment variable, such as `NBPDNS_NETBOX_URL`;\n")
	p("3. the YAML config file named by `--config` or `%s`;\n", ConfigEnv)
	p("4. the default.\n\n")
	p("An empty environment variable counts as unset. An unknown key in the config\n")
	p("file, or an unknown `%s` variable, is an error. nbpdns reports every problem\n", EnvPrefix)
	p("it finds before it stops. To see each key's value and where it came from, run\n")
	p("`nbpdns config show`.\n\n")
	p("A **secret**, such as `netbox.token`, can also be read from a file. Name the\n")
	p("file with the key's `_FILE` environment variable, its `-file` flag, or its\n")
	p("`_file` key in the config file. The file counts at the same level as the key\n")
	p("itself, and setting both at one level is an error. nbpdns never prints or logs\n")
	p("a secret's value.\n\n")

	p("| Key | Type | Default |\n|---|---|---|\n")
	for _, k := range ks {
		p("| [`%s`](#%s) | %s | %s |\n", k.Name, anchor(k.Name), k.typ, code(k.Default))
	}
	p("| [`%s`](#%s) | list of server groups, config file only | none |\n", GroupsKey, anchor(GroupsKey))

	for _, k := range ks {
		p("\n## `%s`\n\n", k.Name)
		p("%s\n", wrap(strings.TrimSpace(k.Summary+" "+k.Details), 79))
		p("\n- **Type:** %s\n", k.typ)
		p("- **Default:** %s\n", code(k.Default))
		p("- **Environment variable:** `%s`\n", k.Env())
		p("- **Flag:** `--%s`\n", k.Flag())
		if k.Secret {
			p("- **From a file:** `%s`, `--%s`, or `%s` in the config file\n", k.FileEnv(), k.FileFlag(), k.FileName())
		}
		if k.Warning != "" {
			p("\n> [!WARNING]\n%s\n", quote(wrap(k.Warning, 77)))
		}
	}

	writeGroupsReference(p)

	p("\n## Example config file\n\n")
	p("Every key except the secrets, with its default:\n\n")
	p("```yaml\n%s```\n", exampleYAML(ks))

	_, err := io.WriteString(w, b.String())
	return err
}

// writeGroupsReference writes the section on powerdns.groups, from its
// fields.
func writeGroupsReference(p func(string, ...any)) {
	p("\n## `%s`\n\n", GroupsKey)
	p("%s\n\n", wrap("The PowerDNS server groups. Each entry is one group: the NetBox views whose "+
		"zones it serves, and its primary, the server nbpdns reads through the PowerDNS API. "+
		"A view may be served by more than one group, as independent sites can serve the same zones.", 79))
	p("%s\n\n", wrap("Groups are resources, not settings, so only the config file declares them: "+
		"there's no environment variable or flag. `nbpdns config show` lists each field of each group, "+
		"such as `powerdns.groups.site-a.primary.url`. An unknown field is an error.", 79))
	p("| Field | Type | Default | Description |\n|---|---|---|---|\n")
	for _, f := range GroupFields() {
		def := code(f.Default)
		if f.Required {
			def = "required"
		}
		p("| `%s` | %s | %s | %s |\n", f.Name, f.Type, def, f.Summary)
	}
	p("\n> [!WARNING]\n%s\n", quote(wrap("A PowerDNS API key can't be limited: it can change every zone, record, "+
		"TSIG key and DNSSEC key on its server. With an `http://` `primary.url`, the key crosses the network "+
		"unencrypted, and anyone on the path can read it. Put the API behind a TLS proxy wherever you can; "+
		"nbpdns logs a warning each time it connects to a primary over `http://`.", 77)))
	p("\nFor example:\n\n")
	p("```yaml\npowerdns:\n  groups:\n")
	p("    - name: site-a\n      views: [_default_]\n      primary:\n")
	p("        url: https://pdns-a.example.com:8443\n        api_key_file: /run/secrets/pdns-site-a\n")
	p("        ca_file: /etc/nbpdns/pdns-ca.pem\n")
	p("    - name: site-b\n      views: [_default_, internal]\n      primary:\n")
	p("        url: https://pdns-b.example.com:8443\n        api_key_file: /run/secrets/pdns-site-b\n")
	p("```\n")
}

// exampleYAML renders every non-secret key with its default, nested the way
// the config file nests them.
func exampleYAML(ks []Key) string {
	var b strings.Builder
	var parent string
	for _, k := range ks {
		if k.Secret {
			continue
		}
		group, leaf, _ := strings.Cut(k.Name, ".")
		if group != parent {
			fmt.Fprintf(&b, "%s:\n", group)
			parent = group
		}
		v := k.Default
		if v == "" {
			v = `""`
		}
		fmt.Fprintf(&b, "  %s: %s\n", leaf, v)
	}
	return b.String()
}

// anchor is the heading ID that GitHub, GitLab and Hugo give "`name`".
func anchor(name string) string { return strings.ReplaceAll(name, ".", "") }

// code formats a default for Markdown, or says there's none.
func code(s string) string {
	if s == "" {
		return "none"
	}
	return "`" + s + "`"
}

// quote turns text into a Markdown blockquote.
func quote(text string) string {
	return "> " + strings.ReplaceAll(text, "\n", "\n> ")
}

// wrap breaks text into lines of at most width characters, between words.
func wrap(text string, width int) string {
	var b strings.Builder
	n := 0
	for i, w := range strings.Fields(text) {
		switch {
		case i == 0:
		case n+1+len(w) > width:
			b.WriteByte('\n')
			n = 0
		default:
			b.WriteByte(' ')
			n++
		}
		b.WriteString(w)
		n += len(w)
	}
	return b.String()
}
