package main

import (
	"cmp"
	"errors"
	"fmt"
	"maps"
	"os"
	"path/filepath"
	"slices"
	"strings"
)

const (
	adrIndexStart = "<!-- projctl:adr-index:start -->"
	adrIndexEnd   = "<!-- projctl:adr-index:end -->"
)

// statusOrder sorts items on the board: active work first, closed work last.
var statusOrder = map[string]int{"in-progress": 0, "open": 1, "blocked": 2, "done": 3, "wontfix": 4}

// Generated is a file projctl owns, with the content it should have.
type Generated struct {
	Path    string
	Content string
}

// generate computes every generated file from the loaded repo.
func generate(r *Repo) ([]Generated, error) {
	adrIndex, err := os.ReadFile(filepath.Join(r.Root, adrIndexMD))
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return nil, err
	}
	spliced, err := spliceADRIndex(string(adrIndex), renderADRTable(r))
	if err != nil {
		return nil, fmt.Errorf("%s: %w", adrIndexMD, err)
	}
	return []Generated{
		{boardMD, renderBoard(r)},
		{adrIndexMD, spliced},
	}, nil
}

// writeGenerated writes every generated file.
func writeGenerated(r *Repo) error {
	gen, err := generate(r)
	if err != nil {
		return err
	}
	for _, g := range gen {
		if err := os.WriteFile(filepath.Join(r.Root, g.Path), []byte(g.Content), 0o644); err != nil {
			return err
		}
	}
	return nil
}

func renderBoard(r *Repo) string {
	var b strings.Builder
	w := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	w("# Project board\n\n")
	w("<!-- Generated by projctl from project/ and docs/adr/. Run `make project`; don't edit by hand. -->\n\n")

	cur := r.Current()
	if cur == nil {
		w("**Current milestone:** none in progress\n\n")
	} else {
		w("**Current milestone:** [%s %s](%s), in progress\n", cur.FM.ID, cur.FM.Title, relBoard(cur.Path))
		if next := r.nextItem(cur); next != nil {
			w("**Next item:** [%s](%s) %s\n\n", next.FM.ID, relBoard(next.Path), next.FM.Title)
		} else {
			w("**Next item:** none; every item is done or waiting on something\n\n")
		}
	}

	w("## Milestones\n\n| Milestone | Title | Status | Items closed |\n|---|---|---|---|\n")
	for _, m := range r.Milestones {
		total, closed := 0, 0
		for _, it := range r.Items {
			if it.FM.Milestone == m.FM.ID {
				total++
				if it.Closed() {
					closed++
				}
			}
		}
		count := "—"
		if total > 0 {
			count = fmt.Sprintf("%d of %d", closed, total)
		}
		w("| [%s](%s) | %s | %s | %s |\n", m.FM.ID, relBoard(m.Path), m.FM.Title, m.FM.Status, count)
	}
	w("\n")

	if cur != nil {
		w("## Items: %s %s\n\n", cur.FM.ID, cur.FM.Title)
		r.itemTable(&b, func(it *Item) bool { return it.FM.Milestone == cur.FM.ID })
	}
	others := func(it *Item) bool { return (cur == nil || it.FM.Milestone != cur.FM.ID) && !it.Closed() }
	if slices.ContainsFunc(r.Items, others) {
		w("## Open items in other milestones\n\n")
		r.itemTable(&b, others)
	}

	q := r.Reqs
	var blocking []string
	neededBy := map[string][]string{}
	for _, o := range q.Open {
		if o.Blocking {
			blocking = append(blocking, o.ID)
		}
		neededBy[o.NeededBy] = append(neededBy[o.NeededBy], o.ID)
	}
	w("## Open questions\n\n")
	w("%d open (%d blocking), %d answered. The questions and their proposed defaults are in [requirements.md](requirements.md#open-questions).\n\n",
		len(q.Open), len(blocking), len(q.Answered))
	if len(blocking) > 0 {
		w("**Blocking:** %s\n\n", strings.Join(blocking, ", "))
	}
	if len(neededBy) > 0 {
		w("| Needed by | Open questions |\n|---|---|\n")
		for _, k := range slices.Sorted(maps.Keys(neededBy)) {
			slices.Sort(neededBy[k])
			w("| %s | %s |\n", k, strings.Join(neededBy[k], ", "))
		}
		w("\n")
	}

	covered := map[string]bool{}
	for _, it := range r.Items {
		for _, req := range it.FM.Requirements {
			covered[req] = true
		}
	}
	var uncovered []string
	for _, req := range q.Reqs {
		if !covered[req] {
			uncovered = append(uncovered, req)
		}
	}
	w("## Requirements\n\n")
	w("%d requirements, listed in [requirements.md](requirements.md#requirements). ", len(q.Reqs))
	if len(uncovered) == 0 {
		w("Every one is referenced by at least one item.\n\n")
	} else {
		verb := "aren't"
		if len(uncovered) == 1 {
			verb = "isn't"
		}
		w("%d %s referenced by any item yet: %s.\n\n", len(uncovered), verb, strings.Join(uncovered, ", "))
	}

	statuses := map[string]int{}
	for _, a := range r.ADRs {
		s := a.FM.Status
		if strings.HasPrefix(s, "superseded") {
			s = "superseded"
		}
		statuses[s]++
	}
	var parts []string
	for _, s := range slices.Sorted(maps.Keys(statuses)) {
		parts = append(parts, fmt.Sprintf("%d %s", statuses[s], s))
	}
	w("## Decisions\n\n%d ADRs (%s), listed in [docs/adr](../docs/adr/_index.md).\n", len(r.ADRs), strings.Join(parts, ", "))
	return b.String()
}

func (r *Repo) itemTable(b *strings.Builder, keep func(*Item) bool) {
	var rows []*Item
	for _, it := range r.Items {
		if keep(it) {
			rows = append(rows, it)
		}
	}
	slices.SortStableFunc(rows, func(a, b *Item) int {
		return cmp.Or(cmp.Compare(statusOrder[a.FM.Status], statusOrder[b.FM.Status]), cmp.Compare(a.FM.ID, b.FM.ID))
	})
	fmt.Fprintf(b, "| Item | Title | Type | Status | Waiting on |\n|---|---|---|---|---|\n")
	for _, it := range rows {
		status := it.FM.Status
		if it.Closed() && it.FM.Closed != "" {
			status += " " + it.FM.Closed
		}
		waiting := "—"
		if !it.Closed() {
			if u := r.Unresolved(it); len(u) > 0 {
				waiting = strings.Join(u, ", ")
			}
		}
		fmt.Fprintf(b, "| [%s](%s) | %s | %s | %s | %s |\n", it.FM.ID, relBoard(it.Path), it.FM.Title, it.FM.Type, status, waiting)
	}
	b.WriteString("\n")
}

// nextItem is the first in-progress item, else the first open one, in the
// milestone that isn't waiting on anything.
func (r *Repo) nextItem(m *Milestone) *Item {
	var best *Item
	for _, it := range r.Items {
		if it.FM.Milestone != m.FM.ID || (it.FM.Status != "in-progress" && it.FM.Status != "open") || len(r.Unresolved(it)) > 0 {
			continue
		}
		if best == nil || statusOrder[it.FM.Status] < statusOrder[best.FM.Status] {
			best = it
		}
	}
	return best
}

func renderADRTable(r *Repo) string {
	var b strings.Builder
	b.WriteString("| ADR | Title | Status |\n|---|---|---|\n")
	for _, a := range r.ADRs {
		fmt.Fprintf(&b, "| [%s](%s) | %s | %s |\n", a.Number, filepath.Base(a.Path), a.ShortTitle(), a.FM.Status)
	}
	return b.String()
}

// spliceADRIndex replaces the text between the ADR index markers.
func spliceADRIndex(doc, table string) (string, error) {
	start := strings.Index(doc, adrIndexStart)
	end := strings.Index(doc, adrIndexEnd)
	if start < 0 || end < start {
		return "", fmt.Errorf("missing %s … %s markers", adrIndexStart, adrIndexEnd)
	}
	return doc[:start+len(adrIndexStart)] + "\n\n" + table + "\n" + doc[end:], nil
}

// relBoard turns a repo-relative path into a link relative to project/.
func relBoard(p string) string {
	rel, err := filepath.Rel("project", p)
	if err != nil {
		return p
	}
	return filepath.ToSlash(rel)
}
