package metrics

import (
	"fmt"
	"io"
	"strconv"
	"strings"
)

// WriteReference writes the metrics reference page, from the declarations.
func WriteReference(w io.Writer) error {
	var b strings.Builder
	p := func(format string, args ...any) { fmt.Fprintf(&b, format, args...) }

	p("---\ntitle: Metrics\nweight: 40\n---\n\n")
	p("<!-- Generated by internal/cmd/gendocs from the metric declarations in internal/metrics.\n")
	p("     Don't edit this page: change the declarations, then run `make generate`. -->\n\n")
	p("# Metrics\n\n")
	p("`nbpdns serve` exposes these metrics at `/metrics`, in Prometheus's text\n")
	p("format, or in OpenMetrics if the scraper asks for it. The other commands\n")
	p("expose none. They're nbpdns's own metrics: PowerDNS's statistics stay on\n")
	p("PowerDNS's own `/metrics`.\n\n")
	p("| Metric | Type | Labels | Description |\n|---|---|---|---|\n")
	for _, d := range defs {
		labels := "none"
		if len(d.labels) > 0 {
			ls := make([]string, len(d.labels))
			for i, l := range d.labels {
				ls[i] = "`" + l + "`"
				if vs := d.values[l]; len(vs) > 0 {
					ls[i] += ": `" + strings.Join(vs, "`, `") + "`"
				}
			}
			labels = strings.Join(ls, "; ")
		}
		help := d.help
		if len(d.buckets) > 0 {
			bs := make([]string, len(d.buckets))
			for i, v := range d.buckets {
				bs[i] = strconv.FormatFloat(v, 'f', -1, 64)
			}
			help += " Buckets, in seconds: " + strings.Join(bs, ", ") + "."
		}
		p("| `%s` | %s | %s | %s |\n", d.name, d.kind, labels, help)
	}
	p("\nThe Prometheus client's standard collectors add the `go_*` metrics of the Go\n")
	p("runtime, and the `process_*` metrics of the process.\n")
	_, err := io.WriteString(w, b.String())
	return err
}
